import{load,save,clear}from'./storage.js';
import{showView}from'./navigation.js';
import{renderQuestion}from'./assessment.js';
import{calculate,dependencyRoute,roadmap,dimNames}from'./engine.js';
import{normalizeAssessment}from'./data.js';

const $=s=>document.querySelector(s);
const get=async p=>{const res=await fetch(p);if(!res.ok)throw new Error(`No se pudo cargar ${p} (${res.status})`);return res.json()};
let questions=[],knowledge={},deps={},maturity=[],resources={intentions:[]},state=load(),dims=[];
state.context=state.context||{businessName:'',businessSize:'',digitalState:'',businessChallenge:''};
const dimLabel=d=>dimNames[d]||d;
const persist=()=>save(state);

function setupNeeds(){const grid=$('#intentGrid');grid.innerHTML='';resources.intentions.forEach((x,i)=>{const b=document.createElement('button');b.className='intent-card'+(state.intent===x.id?' selected':'');b.innerHTML=`<p class="eyebrow">${String(i+1).padStart(2,'0')}</p><b>${x.title}</b><span>${x.focus.length?'Enfoca: '+x.focus.map(dimLabel).join(' · '):'El diagnóstico te ayudará a descubrir prioridades.'}</span>`;b.onclick=()=>{state.intent=x.id;persist();setupNeeds()};grid.appendChild(b)})}
function setupRail(){const r=$('#dimensionRail');r.innerHTML='';dims.forEach(d=>{const qs=questions.filter(q=>q.dimension===d),done=qs.filter(q=>state.answers[q.id]!=null).length;const x=document.createElement('div');x.className='rail-item'+(done===qs.length?' done':'');x.dataset.dim=d;x.innerHTML=`<span>${dimLabel(d)}</span><span>${done}/${qs.length}</span>`;r.appendChild(x)})}
function showQuestion(){if(!questions.length)return;state.index=Math.max(0,Math.min(state.index,questions.length-1));setupRail();renderQuestion({questions,state,onSelect:(q,score)=>{state.answers[q.id]=score;persist();showQuestion()}})}
function complete(){if(Object.keys(state.answers).length<questions.length)return;state.result=calculate(questions,state.answers,maturity);persist();renderResults();$('#resultNav').disabled=false;showView('results')}
function list(id,arr){$(id).innerHTML=arr.map(([d,s],i)=>`<div class="result-item"><span>${i+1}. ${dimLabel(d)}</span><b>${s}/100</b></div>`).join('')}
function renderResults(){const r=state.result;if(!r)return;$('#score').textContent=r.overall;$('#maturity').textContent=r.level.label;$('#maturityDesc').textContent=r.level.description;const bars=$('#bars');bars.innerHTML='';Object.entries(r.dimensions).forEach(([d,s])=>bars.insertAdjacentHTML('beforeend',`<div class="bar-row"><span>${dimLabel(d)}</span><div class="bar-track"><div class="bar-fill" style="width:${s}%"></div></div><b>${s}</b></div>`));list('#strengths',r.strengths);list('#gaps',r.gaps);list('#priorities',r.priorities);const path=dependencyRoute(r,deps);$('#dependencyIntro').textContent=path.length>1?`La brecha principal es ${dimLabel(r.gaps[0][0])}, pero antes conviene fortalecer capacidades que la habilitan.`:`La brecha principal puede trabajarse directamente, manteniendo seguimiento sobre las capacidades relacionadas.`;$('#dependencyPath').innerHTML=path.map((d,i)=>`${i?'<span class="dep-arrow">→</span>':''}<span class="dep-node">${dimLabel(d)} · ${r.dimensions[d]}</span>`).join('');$('#knowledgeCards').innerHTML=r.gaps.map(([d,s])=>knowledgeCard(d,s)).join('');$('#roadmap').innerHTML=roadmap(r,deps).map((x,i)=>`<article class="road-step"><small>${String(i+1).padStart(2,'0')} · ${x.phase}</small><h3>${dimLabel(x.dim)}</h3><p>${knowledge[x.dim]?.actions?.[0]||'Fortalecer esta capacidad.'}</p></article>`).join('');const intent=resources.intentions.find(x=>x.id===state.intent)?.title||'No definido';const business=state.context?.businessName?` Negocio: ${state.context.businessName}.`:'';const challenge=state.context?.businessChallenge?` Reto actual: ${state.context.businessChallenge}.`:'';const msg=`Hola YEHIIBHII Estudio.${business}${challenge} Realicé el Experience Engine V5. Resultado: ${r.overall}/100 (${r.level.label}). Objetivo: ${intent}. Brechas principales: ${r.gaps.map(x=>dimLabel(x[0])).join(', ')}. Me gustaría revisar la ruta recomendada.`;$('#whatsapp').href=`https://wa.me/?text=${encodeURIComponent(msg)}`}
function knowledgeCard(d,s){const k=knowledge[d];if(!k)return'';return`<article class="knowledge-card"><p class="eyebrow">${dimLabel(d)} · ${s}/100</p><p>${k.interpretation}</p><div class="tags">${k.methods.map(m=>`<span class="tag">${m}</span>`).join('')}</div>${k.resources.map(x=>`<a class="resource-link" href="${x.url}" target="_blank" rel="noopener">${x.title} ↗</a>`).join('')}</article>`}
function setupEcosystem(){const g=$('#ecosystemGrid');g.innerHTML='';Object.entries(knowledge).forEach(([d,k],i)=>{const c=document.createElement('article');c.className='eco-card';c.innerHTML=`<p class="eyebrow">${String(i+1).padStart(2,'0')}</p><h3>${dimLabel(d)}</h3><p>${k.interpretation.slice(0,125)}…</p>`;c.onclick=()=>openModal(d);g.appendChild(c)})}
function openModal(d){const k=knowledge[d];if(!k)return;$('#modalBody').innerHTML=`<p class="eyebrow">CAPACIDAD YEHIIBHII</p><h3>${dimLabel(d)}</h3><p>${k.interpretation}</p><h4>Acciones sugeridas</h4><ul>${k.actions.map(x=>`<li>${x}</li>`).join('')}</ul><div class="tags">${k.methods.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h4>Recursos relacionados</h4>${k.resources.map(x=>`<a class="resource-link" href="${x.url}" target="_blank" rel="noopener">${x.title} ↗</a>`).join('')}`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const id=b.dataset.nav;if(id==='results'&&!state.result)return;if(id==='assessment')showQuestion();showView(id)}));$('#needsContinue').onclick=()=>{syncContextForm();showView('context')};$('#contextContinue').onclick=()=>{saveContextForm();state.index=Number.isInteger(state.index)?state.index:0;persist();showQuestion();showView('assessment')};$('#back').onclick=()=>{if(state.index>0){state.index--;persist();showQuestion()}};$('#next').onclick=()=>{if(state.index<questions.length-1){state.index++;persist();showQuestion()}else complete()};$('#resetAssessment').onclick=()=>{if(confirm('¿Reiniciar las respuestas del diagnóstico?')){state={answers:{},index:0,intent:state.intent,result:null,context:state.context};clear();persist();$('#resultNav').disabled=true;showQuestion()}};$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});document.querySelectorAll('.node').forEach(n=>n.onclick=()=>openModal(n.dataset.dim))}

function syncContextForm(){const c=state.context||{};if($('#businessName'))$('#businessName').value=c.businessName||'';if($('#businessSize'))$('#businessSize').value=c.businessSize||'';if($('#digitalState'))$('#digitalState').value=c.digitalState||'';if($('#businessChallenge'))$('#businessChallenge').value=c.businessChallenge||''}
function saveContextForm(){state.context={businessName:$('#businessName')?.value.trim()||'',businessSize:$('#businessSize')?.value||'',digitalState:$('#digitalState')?.value||'',businessChallenge:$('#businessChallenge')?.value.trim()||''};persist()}
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
function showFatal(error){console.error(error);document.body.insertAdjacentHTML('afterbegin',`<div class="fatal"><b>Experience Engine no pudo iniciar.</b><span>${error.message}. Abre el proyecto mediante un servidor local (por ejemplo Live Server), no con file://.</span></div>`)}
async function init(){try{const [rawQuestions,k,d,m,r]=await Promise.all([get('./data/questions.json'),get('./data/knowledge-map.json'),get('./data/dependencies.json'),get('./data/maturity.json'),get('./data/resources.json')]);questions=normalizeAssessment(rawQuestions);knowledge=k;deps=d;maturity=m;resources=r;dims=[...new Set(questions.map(q=>q.dimension))];if(questions.length!==40)throw new Error(`Se esperaban 40 preguntas y se cargaron ${questions.length}`);bind();setupNeeds();setupEcosystem();syncContextForm();if(state.result){$('#resultNav').disabled=false;renderResults()}showQuestion()}catch(error){showFatal(error)}}
init();
import './tools-menu.js';
